spring:
  cloud:
    stream:
      kafka:
        binder:
          # 配置在使用kafka发送消息时kafka节点信息
          brokers: localhost:9092
          # 配置在kafka启动时连接zookeeper的地址
          zk-nodes: localhost:2181
      # spring cloud stream默认绑定kafka消息中间件
      default-binder: kafka
      bindings:
        # 定义sink消费消息的topic
        input:
          destination: usage-cost

# sink应用启动的端口号
server:
  port: 9012