spring:
  cloud:
    stream:
      bindings:
        # 设置spring cloud stream @source 消息输出到kafka的地址
        output:
          destination: usage-detail
      kafka:
        binder:
          # 配置在kafka启动时连接zookeeper的地址
          zk-nodes: 192.168.170.128:2181
          # 配置在使用kafka发送消息时kafka节点信息
          brokers: 192.168.170.128:9092
      # spring cloud stream默认绑定kafka消息中间件
      default-binder: kafka

# 应用启动的端口为9091
server:
  port: 9091